# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 20:22
from __future__ import unicode_literals
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0011_official_resource_sub_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptureBook',
            fields=[
                ('book_num', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(help_text=b'a 3 character abbreviation', max_length=3)),
                ('long_name', models.CharField(help_text=b'the full name', max_length=50)),
            ],
        ),

        migrations.RunSQL(
            "INSERT INTO publishing_scripturebook "
            "  (book_num, short_name, long_name) "
            "VALUES "
            "  (1, 'gen', 'Genesis'), "
            "  (2, 'exo', 'Exodus'), "
            "  (3, 'lev', 'Leviticus'), "
            "  (4, 'num', 'Numbers'), "
            "  (5, 'deu', 'Deuteronomy'), "
            "  (6, 'jos', 'Joshua'), "
            "  (7, 'jdg', 'Judges'), "
            "  (8, 'rut', 'Ruth'), "
            "  (9, '1sa', '1 Samuel'), "
            "  (10, '2sa', '2 Samuel'), "
            "  (11, '1ki', '1 Kings'), "
            "  (12, '2ki', '2 Kings'), "
            "  (13, '1ch', '1 Chronicles'), "
            "  (14, '2ch', '2 Chronicles'), "
            "  (15, 'ezr', 'Ezra'), "
            "  (16, 'neh', 'Nehemiah'), "
            "  (17, 'est', 'Esther'), "
            "  (18, 'job', 'Job'), "
            "  (19, 'psa', 'Psalms'), "
            "  (20, 'pro', 'Proverbs'), "
            "  (21, 'ecc', 'Ecclesiastes'), "
            "  (22, 'sng', 'Song of Solomon'), "
            "  (23, 'isa', 'Isaiah'), "
            "  (24, 'jer', 'Jeremiah'), "
            "  (25, 'lam', 'Lamentations'), "
            "  (26, 'ezk', 'Ezekiel'), "
            "  (27, 'dan', 'Daniel'), "
            "  (28, 'hos', 'Hosea'), "
            "  (29, 'jol', 'Joel'), "
            "  (30, 'amo', 'Amos'), "
            "  (31, 'oba', 'Obadiah'), "
            "  (32, 'jon', 'Jonah'), "
            "  (33, 'mic', 'Micah'), "
            "  (34, 'nam', 'Nahum'), "
            "  (35, 'hab', 'Habakkuk'), "
            "  (36, 'zep', 'Zephaniah'), "
            "  (37, 'hag', 'Haggai'), "
            "  (38, 'zec', 'Zechariah'), "
            "  (39, 'mal', 'Malachi'), "
            "  (41, 'mat', 'Matthew'), "
            "  (42, 'mrk', 'Mark'), "
            "  (43, 'luk', 'Luke'), "
            "  (44, 'jhn', 'John'), "
            "  (45, 'act', 'Acts'), "
            "  (46, 'rom', 'Romans'), "
            "  (47, '1co', '1 Corinthians'), "
            "  (48, '2co', '2 Corinthians'), "
            "  (49, 'gal', 'Galatians'), "
            "  (50, 'eph', 'Ephesians'), "
            "  (51, 'php', 'Philippians'), "
            "  (52, 'col', 'Colossians'), "
            "  (53, '1th', '1 Thessalonians'), "
            "  (54, '2th', '2 Thessalonians'), "
            "  (55, '1ti', '1 Timothy'), "
            "  (56, '2ti', '2 Timothy'), "
            "  (57, 'tit', 'Titus'), "
            "  (58, 'phm', 'Philemon'), "
            "  (59, 'heb', 'Hebrews'), "
            "  (60, 'jas', 'James'), "
            "  (61, '1pe', '1 Peter'), "
            "  (62, '2pe', '2 Peter'), "
            "  (63, '1jn', '1 John'), "
            "  (64, '2jn', '2 John'), "
            "  (65, '3jn', '3 John'), "
            "  (66, 'jud', 'Jude'), "
            "  (67, 'rev', 'Revelation')"),
    ]
